data_list2 = [
    {
        'id': 1,
        'name': '10-Day Green Smoothie Cleanse',
        'author': 'JJ Smith',
        'user_rating': 4.7,
        'number_of_reviews': 17350,
        'price': 8,
        'year': 2016,
        'genre': 'Non Fiction',
    },
    {
        'id': 10,
        'name': 'A Man Called Ove: A Novel',
        'author': 'Fredrik Backman',
        'user_rating': 4.6,
        'number_of_reviews': 23848,
        'price': 8,
        'year': 2016,
        'genre': 'Fiction',
    },
    {
        'id': 11,
        'name': 'A Man Called Ove: A Novel',
        'author': 'Fredrik Backman',
        'user_rating': 4.6,
        'number_of_reviews': 23848,
        'price': 8,
        'year': 2017,
        'genre': 'Fiction',
    },
    {
        'id': 2,
        'name': '11/22/63: A Novel',
        'author': 'Stephen King',
        'user_rating': 4.6,
        'number_of_reviews': 2052,
        'price': 22,
        'year': 2011,
        'genre': 'Fiction',
    },
    {
        'id': 3,
        'name': '12 Rules for Life: An Antidote to Chaos',
        'author': 'Jordan B. Peterson',
        'user_rating': 4.7,
        'number_of_reviews': 18979,
        'price': 15,
        'year': 2018,
        'genre': 'Non Fiction',
    }   
]